"""create reviews table

Revision ID: 33d002fcf932
Revises: 26622275c488
Create Date: 2025-11-19 00:21:21.027363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d002fcf932'
down_revision: Union[str, Sequence[str], None] = '26622275c488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_number', sa.String(length=64), nullable=False),
    sa.Column('user_name', sa.String(length=128), nullable=False),
    sa.Column('product_name', sa.String(length=256), nullable=False),
    sa.Column('product_review', sa.Text(), nullable=False),
    sa.Column('preferred_contact_method', sa.String(length=128), nullable=True),
    sa.Column('preferred_contact_again', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_reviews_contact_number'), 'reviews', ['contact_number'], unique=False)
    op.create_index(op.f('ix_reviews_review_id'), 'reviews', ['review_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_review_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_contact_number'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
