"""create conversation_states table

Revision ID: 7a7d644b8a33
Revises: 33d002fcf932
Create Date: 2025-01-27 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a7d644b8a33'
down_revision: Union[str, Sequence[str], None] = '33d002fcf932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_states',
    sa.Column('state_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_number', sa.String(length=64), nullable=False),
    sa.Column('current_step', sa.Enum('WAITING_NAME', 'WAITING_PRODUCT_NAME', 'WAITING_PRODUCT_REVIEW', 'WAITING_CONTACT_AGAIN', 'WAITING_CONTACT_METHOD', 'COMPLETED', name='conversationstep'), nullable=False),
    sa.Column('user_name', sa.String(length=128), nullable=True),
    sa.Column('product_name', sa.String(length=256), nullable=True),
    sa.Column('product_review', sa.Text(), nullable=True),
    sa.Column('wants_contact_again', sa.String(length=10), nullable=True),
    sa.Column('preferred_contact_method', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_index(op.f('ix_conversation_states_contact_number'), 'conversation_states', ['contact_number'], unique=True)
    op.create_index(op.f('ix_conversation_states_state_id'), 'conversation_states', ['state_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_states_state_id'), table_name='conversation_states')
    op.drop_index(op.f('ix_conversation_states_contact_number'), table_name='conversation_states')
    op.drop_table('conversation_states')
    # ### end Alembic commands ###
